version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    volumes:
      - kafka_kraft:/var/lib/kafka/data

  db:
    image: postgres:16-alpine
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: kafka_project
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azerty@147
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  order_producer:
    build: ./order_producer
    depends_on:
      - kafka
    ports:
      - "8010:8010"
    environment:
      KAFKA_BROKER: kafka:9092

  payment_producer:
    build: ./payment_producer
    depends_on:
      - kafka
    ports:
      - "8011:8011"
    environment:
      KAFKA_BROKER: kafka:9092

  order_consumer:
    build: ./order_consumer
    depends_on:
      - kafka
    ports:
      - "8020:8020"
    environment:
      KAFKA_BROKER: kafka:9092

  payment_consumer:
    build: ./payment_consumer
    depends_on:
      - kafka
    ports:
      - "8021:8021"
    environment:
      KAFKA_BROKER: kafka:9092

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  kafka_kraft: